FROM golang:1.14-alpine as builder

LABEL maintainer="Peter Puhov <peterpuhov.github@gmail.com>"

ENV GOPATH /build/go
ENV CGO_ENABLED 0
ENV GO111MODULE on

RUN  \
     apk add git

ENTRYPOINT ["/build/build-server-entrypoint.sh"]
