#FROM golang:1.14-alpine as builder
FROM golang:1.15-buster

LABEL maintainer="Peter Puhov <peterpuhov.github@gmail.com>"

ENV GOPATH /build/go
ENV CGO_ENABLED 0
ENV GO111MODULE on

RUN  \
     apt-get install git

ENTRYPOINT ["/build/build-server-entrypoint.sh"]
