#FROM alpine:3.12
FROM golang:1.15-buster

LABEL maintainer="Peter Puhov <peterpuhov.github@gmail.com>"

ENV GOPATH /build/go
ENV CGO_ENABLED 0
ENV GO111MODULE on

RUN \
     apt-get update \
     &&apt-get install -y ca-certificates time \
     && echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf

ENTRYPOINT ["/build/run-mc-entrypoint.sh"]